# Use an official Nginx image as a parent image
FROM nginx:latest

# Copy frontend files to the default Nginx web server directory
COPY Frontend/ /usr/share/nginx/html

# Copy  CSS file to the Nginx web server directory
COPY Frontend/buyform_style.css /usr/share/nginx/html
COPY Frontend/buyform_style.css /usr/share/nginx/html

# Copy images to the Nginx web server directory
COPY Frontend/Images/ /usr/share/nginx/html/images/

# Copy fonts to the Nginx web server directory
COPY Frontend/Fonts/ /usr/share/nginx/html/fonts/

#Copy JS files
COPY Backend/ /user/share/nginx/html

# Expose port 80 for serving web content
EXPOSE 80
