version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: contact_mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - contact_mongo_data:/data/db
    ports:
      - 27017:27017

  second_mongo:
    image: mongo:latest
    container_name: buy_mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - buy_mongo_data:/data/db
    ports:
      - 27018:27017

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - second_mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_container
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  contact_mongo_data:
  buy_mongo_data: