# Create a ConfigMap to store MongoDB environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example

# Create PersistentVolumeClaims for MongoDB data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contact-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buy-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

# Create Deployments for MongoDB containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-mongo
  template:
    metadata:
      labels:
        app: contact-mongo
    spec:
      containers:
      - name: contact-mongo
        image: mongo:latest
        envFrom:
          - configMapRef:
              name: mongodb-config
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: contact-mongo-pvc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buy-mongo
  template:
    metadata:
      labels:
        app: buy-mongo
    spec:
      containers:
      - name: buy-mongo
        image: mongo:latest
        envFrom:
          - configMapRef:
              name: mongodb-config
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: buy-mongo-pvc

# Create Services for MongoDB containers
apiVersion: v1
kind: Service
metadata:
  name: contact-mongo-service
spec:
  selector:
    app: contact-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

apiVersion: v1
kind: Service
metadata:
  name: buy-mongo-service
spec:
  selector:
    app: buy-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

# Create Deployments and Services for your backend and frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: d20frontend:1.0 
        imagePullPolicy: Always 
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: d20backend:1.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
