# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY Backend/package*.json ./

# Install the application dependencies
RUN npm install

# Copy the backend code to the container
COPY Backend/ ./

# Expose the port that your application will run on
EXPOSE 3000

# Define the command to start your Node.js application
CMD [ "node", "api.js" ]